config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from profiles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls')),
    path('', include('store.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('notification/', include('notification.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views

app_name = 'order'
urlpatterns = [
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
    path('cart-view/', views.cart_view, name='cart'),
    path('remove-item/<int:pk>/', views.remove_item_from_cart, name='remove-item'),
    path('increase-quantity/<int:pk>/', views.increase_cart, name='increase'),
    path('decrease-quantity/<int:pk>/', views.decrease_cart, name='decrease'),
    path('wishlist/', views.wishlist, name='wishlist'),

]

payment/urls.py
from django.urls import path
from payment import views

app_name = 'payment'
urlpatterns = [
    path('checkout/', views.CheckoutTemplateView.as_view(), name='checkout'),
    path('paypal/', views.paypalPaymentMethod, name='paypal_payment'),
]

order/models.py
from django.db import models
from django.contrib.auth import get_user_model

from store.models import Product, VariationValue

User = get_user_model()

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart')
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    size = models.CharField(max_length=100, blank=True, null=True)
    weight = models.CharField(max_length=100, blank=True, null=True)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.quantity} X {self.item}"
    
    def get_total(self):
        total = self.item.price * self.quantity
        float_total = format(total, '0.2f')
        return float_total
    
    def variation_single_price(self):
        sizes = VariationValue.objects.filter(variation='size', product=self.item)
        weights = VariationValue.objects.filter(variation='weight', product=self.item)
        for size in sizes:
            if weights.exists():
                for weight in weights:
                    if weight.name == self.weight:
                        weight_price = weight.price
                    if size.name == self.size:
                        total = size.price + weight_price
                        net_total = total
                        float_total = format(net_total, '0.2f')
                        return float_total
                    else:
                        if size.name == self.size:
                            total = size.price
                            float_total = format(total, '0.2f')
                            return float_total
    def variation_total(self):
        sizes = VariationValue.objects.filter(variation='size', product=self.item)
        weights = VariationValue.objects.filter(variation='weight', product=self.item)
        for size in sizes:
            if weights.exists():
                for weight in weights:
                    if weight.name == self.weight:
                        weight_price = weight.price
                        weight_quantity_price = weight_price * self.quantity
                    if size.name == self.size:
                        total = size.price * self.quantity
                        net_total = total + weight_quantity_price
                        float_total = format(net_total, '0.2f')
                        return float_total
                else:
                    if size.name == self.size:
                        total = size.price * self.quantity
                        float_total = format(total, '0.2f')
                        return float_total


class Order(models.Model):
    PAYMENT_METHOD = (
        ('Cash on Delivery', 'Cash on Delivery'),
        ('PayPal', 'PayPal'),
        ('SSLcommerz', 'SSLcommerz'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_items = models.ManyToManyField(Cart)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    payment_id = models.CharField(max_length=255, blank=True, null=True)
    order_id = models.CharField(max_length=255, blank=True, null=True)
    payment_method = models.CharField(max_length=30, choices=PAYMENT_METHOD, default='Cash on Delivery')

    def get_totals(self):
        total = 0
        for order_item in self. order_items.all():
            if order_item.variation_total():
                total += float(order_item.variation_total())
            elif order_item.variation_single_price():
                total +=float(order_item.variation_single_price())
            else:
                total += float(order_item.get_total())
        return total
    

order/views.py
from django.shortcuts import render, get_object_or_404, redirect

from store.models import Product
from order.models import Cart, Order

from coupon.forms import CouponCodeFrom
from coupon.models import Coupon

from django.utils import timezone

from notification.notification import SendNotification

# Function view
def add_to_cart(request, pk):
    if request.user.is_authenticated:
        item = get_object_or_404(Product, pk=pk)
        order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased=False)
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.order_items.filter(item=item).exists():
                size = request.POST.get('size')
                color = request.POST.get('color')
                quantity = request.POST.get('quantity')
                if quantity:
                    order_item[0].quantity +=int(quantity)
                else:
                    order_item[0].quantity += 1
                order_item[0].size = size
                order_item[0].color = color
                order_item[0].save()
                message = f"Quantity updated"
                SendNotification(request.user, message)
                return redirect('store:product')
            else:
                size = request.POST.get('size')
                color = request.POST.get('color')
                order_item[0].size = size
                order_item[0].color = color
                order.order_items.add(order_item[0])
                message = f"Product added to your cart"
                SendNotification(request.user, message)
                return redirect ('store:product')
        else:
            order = Order(user=request.user)
            order.save()
            order.order_items.add(order_item[0])
            return redirect ('store:product')
    else:
        return redirect('profiles:login')


def cart_view(request):
    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, purchased=False)
        orders = Order.objects.filter(user=request.user, ordered=False)
        if carts.exists() and orders.exists():
            order = orders[0]
            coupon_form = CouponCodeFrom(request.POST)
            if coupon_form.is_valid():
                current_time = timezone.now()
                code = coupon_form.cleaned_data.get('code')
                coupon_obj = Coupon.objects.get(code=code, active=True)
                if coupon_obj.valid_to >= current_time:
                    get_discount = (coupon_obj.discount / 100) * order.get_totals()
                    total_price_after_discount = order.get_totals() - get_discount
                    request.session['discount_total'] = total_price_after_discount
                    request.session['coupon_code'] = code 
                    return redirect('order:cart')
                else:
                    coupon_obj.active = False
                    coupon_obj.save()
                    return redirect('order:cart')
                
            total_price_after_discount = request.session.get('discount_total')
            coupon_code = request.session.get('coupon_code')
            context = {
                'carts': carts,
                'order': order,
                'coupon_form': coupon_form,
                'coupon_code': coupon_code,
                'total_price_after_discount': total_price_after_discount
            }
            return render(request, 'order/cart.html', context)
    else:
        return redirect('profiles:login')

def remove_item_from_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    orders = Order.objects.filter(user=request.user, ordered=False)
    if orders.exists():
        order = orders[0]
        if order.order_items.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            order.order_items.remove(order_item)
            order_item.delete()
            return redirect('order:cart')
        else:
            return redirect('order:cart')
    else:
        return redirect('order:cart')
    
def increase_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.order_items.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            if order_item.quantity >=1:
                order_item.quantity +=1
                order_item.save()
                return redirect('order:cart')
            else:
                return redirect('order:cart')
        else: 
            return redirect('store:index')
    else: 
        return redirect('store:index')
        
def decrease_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.order_items.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user, purchased=False)[0]
            if order_item.quantity >1:
                order_item.quantity -=1
                order_item.save()
                return redirect('order:cart')
            else:
                order.order_items.remove(order_item)
                order_item.delete()
                return redirect('order:cart')
        else: 
            return redirect('store:index')
    else: 
        return redirect('store:index')
    
def wishlist(request):
    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, purchased=False)
        orders = Order.objects.filter(user=request.user, ordered=False)
        if carts.exists() and orders.exists():
            order = orders[0]
            coupon_form = CouponCodeFrom(request.POST)
            if coupon_form.is_valid():
                current_time = timezone.now()
                code = coupon_form.cleaned_data.get('code')
                coupon_obj = Coupon.objects.get(code=code, active=True)
                if coupon_obj.valid_to >= current_time:
                    get_discount = (coupon_obj.discount / 100) * order.get_totals()
                    total_price_after_discount = order.get_totals() - get_discount
                    request.session['discount_total'] = total_price_after_discount
                    request.session['coupon_code'] = code 
                    return redirect('order:cart')
                else:
                    coupon_obj.active = False
                    coupon_obj.save()
                    return redirect('order:cart')
                
            total_price_after_discount = request.session.get('discount_total')
            coupon_code = request.session.get('coupon_code')
            context = {
                'carts': carts,
                'order': order,
                'coupon_form': coupon_form,
                'coupon_code': coupon_code,
                'total_price_after_discount': total_price_after_discount
            }
            return render(request, 'order/wishlist.html', context)
    else:
        return render(request, 'order/wishlist.html')

order/templates/order/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Cart {% endblock title %}

{% block content %}
        <main class="main">
        	<div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
        		<div class="container">
        			<h1 class="page-title">Shopping Cart<span>Shop</span></h1>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->
            <nav aria-label="breadcrumb" class="breadcrumb-nav">
                <div class="container">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Shopping Cart</li>
                    </ol>
                </div><!-- End .container -->
            </nav><!-- End .breadcrumb-nav -->

            <div class="page-content">
            	<div class="cart">
	                <div class="container"> 
	                	<div class="row">
	                		<div class="col-lg-9">
	                			<table class="table table-cart table-mobile">
									<thead>
										<tr>
											<th>Product</th>
											<th>Size</th>
											<th>Weight</th>
											<th>Price</th>
											<th>KG</th>
											<th>Total</th>
											<th></th>
										</tr>
									</thead>

									<tbody>
										{% for cart in carts %}
										<tr>
											<td class="product-col">
												<div class="product">
													<figure class="product-media">
														<a href="#">
															<img src="{{cart.item.image.url}}" alt="Product image">
														</a>
													</figure>

													<h3 class="product-title">
														<a href="#">{{cart.item.title}}</a>
													</h3><!-- End .product-title -->
												</div><!-- End .product -->
											</td>
											<td class="price-col">{{cart.size}}</td>
											<td class="price-col">{{cart.weight}}</td>

											<td class="price-col">
											{% if cart.variation_single_price %}
											 $ {{cart.variation_single_price}}
											{% else %}
												$ {{cart.item.price}}
											{% endif %}
											</td>


											<td class="quantity-col">
                                                <div class="cart-product-quantity">
													<a class="mr-2" href="{% url 'order:decrease' pk=cart.item.pk %}"><span class="badge badge-light"><i class="la la-minus"></i></span></a>
														<span>{{cart.quantity}}</span>
													<a class="mr-2" href="{% url 'order:increase' pk=cart.item.pk %}"><span class="badge badge-light"><i class="la la-plus"></i></span></a>
                                                </div><!-- End .cart-product-quantity -->
                                            </td>
											<td class="total-col">
											{% if cart.variation_total %}
												$ {{cart.variation_total}}
											{% else %}
												$ {{cart.get_total}}
											{% endif %}
											</td>
											<td class="remove-col"><a href="{% url 'order:remove-item' pk=cart.item.pk %}"><button class="btn-remove"><i class="icon-close"></i></button></a></td>
										</tr>
										{% endfor %}
									</tbody>
								</table><!-- End .table table-wishlist -->

	                			<div class="cart-bottom">
			            			<div class="cart-discount">
			            				<form action="" method="POST">
			            					<div class="input-group">
												{% csrf_token %}
												{{coupon_form}}
											<div class="input-group-append">
												<button class="btn btn-outline-primary-2" type="submit"><i class="icon-long-arrow-right"></i></button>
											</div><!-- .End .input-group-append -->
			        						</div><!-- End .input-group -->
			            				</form>
			            			</div><!-- End .cart-discount -->

			            			<a href="#" class="btn btn-outline-dark-2"><span>UPDATE CART</span><i class="icon-refresh"></i></a>
		            			</div><!-- End .cart-bottom -->
	                		</div><!-- End .col-lg-9 -->
	                		<aside class="col-lg-3">
	                			<div class="summary summary-cart">
	                				<h3 class="summary-title">Cart Total</h3><!-- End .summary-title -->

	                				<table class="table table-summary">
	                					<tbody>
	                						<tr class="summary-subtotal">
	                							<td>Subtotal:</td>
	                							<td>$ {{order.get_totals}}</td>
	                						</tr><!-- End .summary-subtotal -->
	                						<tr class="summary-shipping">
	                							<td>Shipping:</td>
	                							<td>&nbsp;</td>
	                						</tr>

	                						<tr class="summary-shipping-row">
	                							<td>
													<div class="custom-control custom-radio">
														<input type="radio" id="free-shipping" name="shipping" class="custom-control-input">
														<label class="custom-control-label" for="free-shipping">Free Shipping</label>
													</div><!-- End .custom-control -->
	                							</td>
	                							<td>$0.00</td>
	                						</tr><!-- End .summary-shipping-row -->

	                						<tr class="summary-shipping-row">
	                							<td>
	                								<div class="custom-control custom-radio">
														<input type="radio" id="standart-shipping" name="shipping" class="custom-control-input">
														<label class="custom-control-label" for="standart-shipping">Standart:</label>
													</div><!-- End .custom-control -->
	                							</td>
	                							<td>$10.00</td>
	                						</tr><!-- End .summary-shipping-row -->

	                						<tr class="summary-shipping-row">
	                							<td>
	                								<div class="custom-control custom-radio">
														<input type="radio" id="express-shipping" name="shipping" class="custom-control-input">
														<label class="custom-control-label" for="express-shipping">Express:</label>
													</div><!-- End .custom-control -->
	                							</td>
	                							<td>$20.00</td>
	                						</tr><!-- End .summary-shipping-row -->

	                						<tr class="summary-shipping-estimate">
	                							<td>Estimate for Your Country<br> <a href="dashboard.html">Change address</a></td>
	                							<td>&nbsp;</td>
	                						</tr><!-- End .summary-shipping-estimate -->

	                						<tr class="summary-total">
	                							<td>Total:</td>
	                							<td>
													{% if total_price_after_discount %}
														$ {{total_price_after_discount}}
													{% else %}
														$ {{order.get_totals}}
													{% endif %}
												</td>
	                						</tr><!-- End .summary-total -->
	                					</tbody>
	                				</table><!-- End .table table-summary -->

	                				<a href="{% url 'payment:checkout' %}" class="btn btn-outline-primary-2 btn-order btn-block">PROCEED TO CHECKOUT</a>
	                			</div><!-- End .summary -->

		            			<a href="category.html" class="btn btn-outline-dark-2 btn-block mb-3"><span>CONTINUE SHOPPING</span><i class="icon-refresh"></i></a>
	                		</aside><!-- End .col-lg-3 -->
	                	</div><!-- End .row -->
	                </div><!-- End .container -->
                </div><!-- End .cart -->
            </div><!-- End .page-content -->
        </main><!-- End .main -->
{% endblock content %}

order/templates/order/wishlist.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Wish List {% endblock title %}

{% block content %}
        <main class="main">
        	<div class="text-center">
        		<div class="container">
        			<h3 class="page-title">Wish List</h3>
					<br>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->

            <div class="page-content">
            	<div class="cart">
	                <div class="container"> 
	                	<div class="row">
	                		<div class="col-lg-9">
	                			<table class="table table-cart table-mobile">
									<thead>
										<tr>
											<th>Product</th>
											<th>Size</th>
											<th>Weight</th>
											<th>Price</th>
											<th>KG</th>
											<th>Total</th>
											<th></th>
										</tr>
									</thead>

									<tbody>
										{% for cart in carts %}
										<tr>
											<td class="product-col">
												<div class="product">
													<figure class="product-media">
														<a href="#">
															<img src="{{cart.item.image.url}}" alt="Product image">
														</a>
													</figure>

													<h3 class="product-title">
														<a href="#">{{cart.item.title}}</a>
													</h3><!-- End .product-title -->
												</div><!-- End .product -->
											</td>
											<td class="price-col">{{cart.size}}</td>
											<td class="price-col">{{cart.weight}}</td>

											<td class="price-col">
											{% if cart.variation_single_price %}
											 $ {{cart.variation_single_price}}
											{% else %}
												$ {{cart.item.price}}
											{% endif %}
											</td>


											<td class="quantity-col">
                                                <div class="cart-product-quantity">
													<a class="mr-2" href="{% url 'order:decrease' pk=cart.item.pk %}"><span class="badge badge-light"><i class="la la-minus"></i></span></a>
														<span>{{cart.quantity}}</span>
													<a class="mr-2" href="{% url 'order:increase' pk=cart.item.pk %}"><span class="badge badge-light"><i class="la la-plus"></i></span></a>
                                                </div><!-- End .cart-product-quantity -->
                                            </td>
											<td class="total-col">
											{% if cart.variation_total %}
												$ {{cart.variation_total}}
											{% else %}
												$ {{cart.get_total}}
											{% endif %}
											</td>
											<td class="remove-col"><a href="{% url 'order:remove-item' pk=cart.item.pk %}"><button class="btn-remove"><i class="icon-close"></i></button></a></td>
										</tr>
										{% endfor %}
									</tbody>
								</table><!-- End .table table-wishlist -->

	                			<div class="cart-bottom">
			            			<div class="cart-discount">
			            				<form action="" method="POST">
			            					<div class="input-group">
												{% csrf_token %}
												{{coupon_form}}
											<div class="input-group-append">
												<button class="btn btn-outline-primary-2" type="submit"><i class="icon-long-arrow-right"></i></button>
											</div><!-- .End .input-group-append -->
			        						</div><!-- End .input-group -->
			            				</form>
			            			</div><!-- End .cart-discount -->

			            			<a href="#" class="btn btn-outline-dark-2"><span>UPDATE CART</span><i class="icon-refresh"></i></a>
		            			</div><!-- End .cart-bottom -->
	                		</div><!-- End .col-lg-9 -->
	                		<aside class="col-lg-3">
	                			<div class="summary summary-cart">
	                				<h3 class="summary-title">Cart Total</h3><!-- End .summary-title -->

	                				<table class="table table-summary">
	                					<tbody>
	                						<tr class="summary-subtotal">
	                							<td>Subtotal:</td>
	                							<td>$ {{order.get_totals}}</td>
	                						</tr><!-- End .summary-subtotal -->
	                						<tr class="summary-shipping">
	                							<td>Shipping:</td>
	                							<td>&nbsp;</td>
	                						</tr>

	                						<tr class="summary-shipping-row">
	                							<td>
													<div class="custom-control custom-radio">
														<input type="radio" id="free-shipping" name="shipping" class="custom-control-input">
														<label class="custom-control-label" for="free-shipping">Free Shipping</label>
													</div><!-- End .custom-control -->
	                							</td>
	                							<td>$0.00</td>
	                						</tr><!-- End .summary-shipping-row -->

	                						<tr class="summary-shipping-row">
	                							<td>
	                								<div class="custom-control custom-radio">
														<input type="radio" id="standart-shipping" name="shipping" class="custom-control-input">
														<label class="custom-control-label" for="standart-shipping">Standart:</label>
													</div><!-- End .custom-control -->
	                							</td>
	                							<td>$10.00</td>
	                						</tr><!-- End .summary-shipping-row -->

	                						<tr class="summary-shipping-row">
	                							<td>
	                								<div class="custom-control custom-radio">
														<input type="radio" id="express-shipping" name="shipping" class="custom-control-input">
														<label class="custom-control-label" for="express-shipping">Express:</label>
													</div><!-- End .custom-control -->
	                							</td>
	                							<td>$20.00</td>
	                						</tr><!-- End .summary-shipping-row -->

	                						<tr class="summary-shipping-estimate">
	                							<td>Estimate for Your Country<br> <a href="dashboard.html">Change address</a></td>
	                							<td>&nbsp;</td>
	                						</tr><!-- End .summary-shipping-estimate -->

	                						<tr class="summary-total">
	                							<td>Total:</td>
	                							<td>
													{% if total_price_after_discount %}
														$ {{total_price_after_discount}}
													{% else %}
														$ {{order.get_totals}}
													{% endif %}
												</td>
	                						</tr><!-- End .summary-total -->
	                					</tbody>
	                				</table><!-- End .table table-summary -->

	                				<a href="{% url 'payment:checkout' %}" class="btn btn-outline-primary-2 btn-order btn-block">PROCEED TO CHECKOUT</a>
	                			</div><!-- End .summary -->

		            			<a href="category.html" class="btn btn-outline-dark-2 btn-block mb-3"><span>CONTINUE SHOPPING</span><i class="icon-refresh"></i></a>
	                		</aside><!-- End .col-lg-3 -->
	                	</div><!-- End .row -->
	                </div><!-- End .container -->
                </div><!-- End .cart -->
            </div><!-- End .page-content -->
        </main><!-- End .main -->
{% endblock content %}