config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from profiles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls')),
    path('', include('store.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('notification/', include('notification.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views

app_name = 'order'
urlpatterns = [
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
    path('cart-view/', views.cart_view, name='cart'),
    path('remove-item/<int:pk>/', views.remove_item_from_cart, name='remove-item'),
    path('increase-quantity/<int:pk>/', views.increase_cart, name='increase'),
    path('decrease-quantity/<int:pk>/', views.decrease_cart, name='decrease'),
    path('wishlist/', views.wishlist, name='wishlist'),

]

profiles/urls.py
from django.urls import path
from profiles import views

app_name = "profiles"
urlpatterns = [
    path('register/', views.Register, name='register'),
    path('login/', views.CustomerLogin, name='login'),
    path('logout/', views.CustomerLogout, name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile' ),

]

store/urls.py
from django.urls import path
from store import views

app_name = "store"
urlpatterns = [
    path('', views.HomeListView.as_view(), name='index'),
    path('product/<slug>/', views.ProductDetailView.as_view(), name='product-details'),
    path('about/', views.about, name='about'),
    path('products/', views.ProductistView.as_view(), name='product'),
]

store/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import default, slugify
from django.contrib.auth import get_user_model

User = get_user_model()

class Category(models.Model):
    title = models.CharField(max_length=150, unique=True)
    slug = models.SlugField(unique=True, max_length=150)
    featured = models.BooleanField(default=False)
    image = models.ImageField(upload_to='category', blank=True, null=True)
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Categories'
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

class Product(models.Model):
    title = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(unique=True, max_length=250)
    category = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE)
    featured = models.BooleanField(default=False)
    preview_des = models.CharField(max_length=255, verbose_name='Short Description')
    description = models.TextField(null=True, blank=True, verbose_name='Description')
    image = models.ImageField(upload_to='products', blank=False, null=False)
    price = models.FloatField()
    old_price = models.FloatField(default=0.00, blank=True, null=True)
    in_stock = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ['-id']

    def get_product_url(self):
        return reverse('store:product-details', kwargs={'slug':self.slug})
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.FileField(upload_to='prodcut_gallery')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.product.title)


class VariationManager(models.Manager):
    def sizes(self):
        return super(VariationManager, self).filter(variation='size')

    def weights(self):
        return super(VariationManager, self).filter(variation='weight')

VARIATIONS_TYPE = (
    ('size', 'size'),
    ('weight', 'weight'),
)
class VariationValue(models.Model):
    variation = models.CharField(max_length=100, choices=VARIATIONS_TYPE)
    name = models.CharField(max_length=50)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='product_variation', blank=True, null=True)

    objects = VariationManager()

    def __str__(self):
        # return self.name
        return f"{self.product} - variation - {self.name}"

class Banner(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='banner')
    image = models.ImageField(upload_to='banner')
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.title
    

store/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, TemplateView

# product models
from store.models import Category, Product, ProductImages, Banner

class HomeListView(TemplateView):
    def get(self, request, *args, **kwargs):
        products = Product.objects.all().order_by('-id')
        banners = Banner.objects.filter(is_active=True).order_by('-id')[0:5]

        context = {
            'products': products,
            'banners': banners
        }
        return render(request, 'store/index.html', context)

    def post(self, request, *args, **kwargs):
        if request.method == 'post' or request.method == 'POST':
            search = request.POST.get('search')
            products = Product.objects.filter(title__icontains=search).order_by('-id')

            context = {
                'products': products
            }
            return render(request, 'store/index.html', context)


# Class Based View
class ProductDetailView(DetailView):
    model = Product
    template_name = 'store/product.html'
    context_object_name = 'item'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_images'] = ProductImages.objects.filter(product=self.object.id)
        return context


# Function based view for item.get_product_url

# def product_details(request, pk):
#     item = Product.objects.get(id=pk)
#     photos = ProductImages.objects.filter(product=item).order_by('-created')
#     context = { 
#         'item': item
#         'photos': photos
#     }
#     return render(request, 'store/product.html', context)

def about(request):
    return render(request, 'store/about.html')

class ProductistView(TemplateView):
    def get(self, request, *args, **kwargs):
        products = Product.objects.all().order_by('-id')

        context = {
            'products': products,
        }
        return render(request, 'store/products.html', context)

    def post(self, request, *args, **kwargs):
        if request.method == 'post' or request.method == 'POST':
            search = request.POST.get('search')
            products = Product.objects.filter(title__icontains=search).order_by('-id')

            context = {
                'products': products
            }
            return render(request, 'store/products.html', context)

store/templates/_footer-old.html
{% load static %}

<!-- Footer Section Begin -->
<footer class="footer-section spad">
    <div class="container">
        <div class="newslatter-form">
            <div class="row">
                <div class="col-lg-12">
                    <form action="#">
                        <input type="text" placeholder="Your email address">
                        <button type="submit">Subscribe to our newsletter</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer-widget">
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="single-footer-widget">
                        <h4>About us</h4>
                        <ul>
                            <li>About Us</li>
                            <li>Community</li>
                            <li>Jobs</li>
                            <li>Shipping</li>
                            <li>Contact Us</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single-footer-widget">
                        <h4>Customer Care</h4>
                        <ul>
                            <li>Search</li>
                            <li>Privacy Policy</li>
                            <li>2019 Lookbook</li>
                            <li>Shipping & Delivery</li>
                            <li>Gallery</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single-footer-widget">
                        <h4>Our Services</h4>
                        <ul>
                            <li>Free Shipping</li>
                            <li>Free Returnes</li>
                            <li>Our Franchising</li>
                            <li>Terms and conditions</li>
                            <li>Privacy Policy</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="single-footer-widget">
                        <h4>Information</h4>
                        <ul>
                            <li>Payment methods</li>
                            <li>Times and shipping costs</li>
                            <li>Product Returns</li>
                            <li>Shipping methods</li>
                            <li>Conformity of the products</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="social-links-warp">
        <div class="container">
            <div class="social-links">
                <a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
                <a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
                <a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
                <a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
                <a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
                <a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
            </div>
        </div>

        <div class="container text-center pt-5">
            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
                with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com"
                    target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

store/templates/_footer.html
{% load theme %}
{% load static %}

<!-- Footer Section Begin -->
<footer class="footer">
    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-lg-3">
                    <div class="widget widget-about">
                        {% for info in settings %}
                        {% if info.logo %}
                        <img src="{{info.logo.url}}" class="footer-logo" alt="{{info.website_title}}" width="105" height="25">
                        {% endif %}
                        {% if info.slogan %}
                        <p>{{info.slogan}}. </p>
                        {% endif %}
                        {% endfor %}
        
                        <div class="social-icons">
                        {% for link in social_links %}
                            <a href="{{link.link}}" class="social-icon" target="_blank" title="{{link.title}}"><img src="{{link.logo.url}}" class="footer-logo" alt="{{link.title}}" width="25" height="25"></a>
                        {%  endfor%}
                        </div><!-- End .soial-icons -->
                    </div><!-- End .widget about-widget -->
                </div><!-- End .col-sm-6 col-lg-3 -->

                <div class="col-sm-6 col-lg-3">
                    <div class="widget">
                        <h4 class="widget-title">Useful Links</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            {% for info in settings %}
                            {% if info.website_title %}
                            <li><a href="{% url 'store:about' %}">About {{info.website_title}}</a></li>
                            {% endif %}
                            {% endfor %}
                            <li><a href="{% url 'store:about' %}">Contact us</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-6 col-lg-3 -->

                <div class="col-sm-6 col-lg-3">
                    <div class="widget">
                        <h4 class="widget-title">Customer Service</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="#">Payment Methods</a></li>
                            <li><a href="#">Shipping</a></li>
                            <li><a href="#">Terms and conditions</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-6 col-lg-3 -->

                <div class="col-sm-6 col-lg-3">
                    <div class="widget">
                        <h4 class="widget-title">My Account</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="{% url 'profiles:login' %}">Sign In</a></li>
                            <li><a href="{% url 'order:cart' %}">View Cart</a></li>
                            <li><a href="{% url 'profiles:profile' %}">My Profile</a></li>
                            <!-- <li><a href="#">My Wishlist</a></li> -->
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-6 col-lg-3 -->
            </div><!-- End .row -->
        </div><!-- End .container -->
    </div><!-- End .footer-middle -->

    <div class="footer-bottom">
        <div class="container">
            {% for info in settings %}
                {% if info.website_title %}
                <p class="footer-copyright">Copyright © 2019 {{info.website_title}}. All Rights Reserved.</p><!-- End .footer-copyright -->
                {% endif %}
            {% endfor %}
            <figure class="footer-payments">
                <!-- <img src="{% static 'assets/images/payments.png' %}" alt="Payment methods" width="272" height="20"> -->
            </figure><!-- End .footer-payments -->
        </div><!-- End .container -->
    </div><!-- End .footer-bottom -->
</footer><!-- End .footer -->
<!-- Footer Section End -->

store/templates/_scripts.html
{% load static %}
    <!-- Plugins JS File -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.hoverIntent.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'assets/js/superfish.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap-input-spinner.js' %}"></script>
    <script src="{% static 'assets/js/jquery.plugin.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.countdown.min.js' %}"></script>
    <!-- Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'assets/js/demos/demo-4.js' %}"></script>

store/templates/_search.html
    <!-- Search model -->
	<div class="search-model">
		<div class="h-100 d-flex align-items-center justify-content-center">
			<div class="search-close-switch">+</div>
			<form class="search-model-form" method="GET" action="#">
				<input name="key" type="text" id="search-input" placeholder="Search here.....">
			</form>
		</div>
	</div>
	<!-- Search model end -->

store/templates/_slider.html
{% load static %}

<!-- Hero Slider Begin -->
<section class="hero-slider">
    <div class="hero-items owl-carousel">
        {% for slider in sliders %}
        <div class="single-slider-item set-bg" data-setbg="{{slider.banner.url}}">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <h2>{{slider.title}}.</h2>
                        <a href="#" class="primary-btn">See More</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
<!-- Hero Slider End -->

store/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="HTML5 Template">
    <meta name="description" content="Molla - Bootstrap eCommerce Template">
    <meta name="author" content="p-themes">
    <title>{% block title %} {% endblock title %}</title>

    <!-- Favicon -->
    {% for info in settings %}
    {% if info.apple_touch_icon_png %}
    <link rel="apple-touch-icon" sizes="180x180" href="{{ info.apple_touch_icon_png.url }}">
    {% endif %}
    {% if info.favicon_png %}
    <link rel="icon" type="image/png" sizes="32x32" href="{{ info.favicon_png.url }}">
    {% endif %}
    {% if info.favicon_png %}
    <link rel="icon" type="image/png" sizes="16x16" href="{{ info.favicon_png.url }}">
    {% endif %}
    <link rel="manifest" href="{% static  'assets/images/icons/site.html' %}">
    <link rel="mask-icon" href="{% static  'assets/images/icons/safari-pinned-tab.svg' %}" color="#666666">
    {% if info.logo %}
        <link rel="shortcut icon" href="{{ info.favicon_ico.url }}">
    {% endif %}
    <meta name="apple-mobile-web-app-title" content="Molla">
    <meta name="application-name" content="Molla">
    {%  endfor%}
    <meta name="msapplication-TileColor" content="#cc9966">
    <meta name="msapplication-config" content="{% static  'assets/images/icons/browserconfig.xml' %}">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static  'assets/vendor/line-awesome/line-awesome/line-awesome/css/line-awesome.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="{% static  'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static  'assets/css/plugins/owl-carousel/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static  'assets/css/plugins/magnific-popup/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static  'assets/css/plugins/jquery.countdown.css' %}">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="{% static  'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static  'assets/css/skins/skin-demo-4.css' %}">
    <link rel="stylesheet" href="{% static  'assets/css/demos/demo-4.css' %}">
    
    {% block links %}
    {% endblock links %}
</head>

<body> 
    {% include '_header.html' %}

    {% block content %}
    {% endblock content %}

    {% include '_footer.html' %}

    {% include '_scripts.html' %}
    {% block paypal %}{% endblock paypal %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

store/templates/message.html
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <strong>{{message.message}}</strong>
</div>
{% endfor %}