config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from profiles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls')),
    path('', include('store.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
    path('notification/', include('notification.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views

app_name = 'order'
urlpatterns = [
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
    path('cart-view/', views.cart_view, name='cart'),
    path('remove-item/<int:pk>/', views.remove_item_from_cart, name='remove-item'),
    path('increase-quantity/<int:pk>/', views.increase_cart, name='increase'),
    path('decrease-quantity/<int:pk>/', views.decrease_cart, name='decrease'),
    path('wishlist/', views.wishlist, name='wishlist'),

]

payment/urls.py
from django.urls import path
from payment import views

app_name = 'payment'
urlpatterns = [
    path('checkout/', views.CheckoutTemplateView.as_view(), name='checkout'),
    path('paypal/', views.paypalPaymentMethod, name='paypal_payment'),
]

store/urls.py
from django.urls import path
from store import views

app_name = "store"
urlpatterns = [
    path('', views.HomeListView.as_view(), name='index'),
    path('product/<slug>/', views.ProductDetailView.as_view(), name='product-details'),
    path('about/', views.about, name='about'),
    path('products/', views.ProductistView.as_view(), name='product'),
]

payment/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class BillingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20, blank=True, null=True)
    last_name = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    address1 = models.TextField(max_length=200, blank=True, null=True)
    address2 = models.TextField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    zipcode = models.CharField(max_length=15, blank=True, null=True)
    phone_number = models.CharField(max_length=16, blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s billing address"
    
    def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]
        for field_name in field_names:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True
 

payment/forms.py
from django import forms
from django.db.models import fields
from payment.models import BillingAddress
from order.models import Order

class BillingAddressForm(forms.ModelForm):
    class Meta: 
        model = BillingAddress
        fields = ('__all__')
        exclude = ('user',)

class PaymentMethodForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['payment_method']

payment/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect

# View
from django.views.generic import TemplateView

#  Models
from payment.models import BillingAddress
from payment.forms import BillingAddressForm, PaymentMethodForm
from order.models import Cart, Order

# PayPal
from django.conf import settings
import json

# SSLcommerz
from sslcommerz_python.payment import SSLCSession

from django.views.decorators.csrf import csrf_exempt
from decimal import Decimal

class CheckoutTemplateView(TemplateView):
    def get(self, request, *args, **kwargs):
        saved_address = BillingAddress.objects.get_or_create(user=request.user or None)
        saved_address = saved_address[0]
        form = BillingAddressForm(instance=saved_address)
        payment_method = PaymentMethodForm()
        order_qs = Order.objects.filter(user=request.user, ordered=False)
        order_item = order_qs[0].order_items.all()
        order_total = order_qs[0].get_totals()

        context = {
            'billing_address': form,
            'order_item': order_item,
            'order_total': order_total,
            'payment_method': payment_method,
            'paypal_client_id': settings.PAYPAL_CLIENT_ID
        }
        return render(request, 'payment/checkout.html', context)

    def post(self, request, *args, **kwargs):
        saved_address = BillingAddress.objects.get_or_create(user=request.user or None)
        saved_address = saved_address[0]
        form = BillingAddressForm(instance=saved_address)
        payment_obj = Order.objects.filter(user=request.user, ordered=False)[0]
        payment_form = PaymentMethodForm(instance=payment_obj)
        if request.method == 'post' or request.method == 'POST':
            form = BillingAddressForm(request.POST, instance=saved_address)
            pay_form = PaymentMethodForm(request.POST, instance=payment_obj)
            if form.is_valid() and pay_form.is_valid():
                form.save()
                pay_method = pay_form.save()

                if not saved_address.is_fully_filled():
                    return redirect('payment:checkout')
                
                # Cash on delivery payment process
                if pay_method.payment_method == 'Cash on Delivery':
                    order_qs = Order.objects.filter(user=request.user, ordered=False)
                    order = order_qs[0]
                    order.ordered = True
                    order.order_id = order.id
                    order.payment_id = order.id
                    order.save()
                    cart_items = Cart.objects.filter(user=request.user, purchased=False)
                    for item in cart_items:
                        item.purchased = True
                        item.save()
                    print('Order Submitted Successfully')
                    return redirect('store:index')
                
                # PayPal payment process
                #if pay_method.payment_method =='PayPal':
                    #return redirect(reverse('payment:checkout') + "?pay_meth=" +str(pay_method.payment_method))
                
                # SSLcommerz payment process
                if pay_method.payment_method == 'SSLcommerz':
                    store_id = settings.STORE_ID
                    store_pass = settings.STORE_PASS
                    mypayment = SSLCSession(sslc_is_sandbox=True, sslc_store_id=store_id, sslc_store_pass=store_pass)

                    status_url = request.build_absolute_uri(reverse('payment:status'))
                    mypayment.set_urls(success_url=status_url, fail_url=status_url, cancel_url=status_url, ipn_url=status_url)

                    order_qs = Order.objects.filter(user=request.user, ordered=False)
                    order_items = order_qs[0].order_items.all()
                    order_item_count = order_qs[0].order_items.count()
                    order_total = order_qs[0].get_totals()
                    mypayment.set_product_integration(total_amount=Decimal(order_total), currency='BDT', product_category='clothing', product_name=order_items, num_of_item=order_item_count, shipping_method='Courier', product_profile='None')

                    current_user = request.user
                    mypayment.set_customer_info(name=current_user.profile.full_name, email=current_user.email, address1=current_user.profile.address, address2=current_user.profile.address, city=current_user.profile.city, postcode=current_user.profile.zip_code, country=current_user.profile.country, phone=current_user.profile.phone)
                    mypayment.set_shipping_info(shipping_to=current_user.profile.full_name, address=current_user.profile.address, city=current_user.profile.city, postcode=current_user.profile.zip_code, country=current_user.profile.country)

                    response_data = mypayment.init_payment()
                    print('==============================================================')
                    print(response_data)
                    return redirect(response_data['GatewayPageURL'])
                    print('==================================================================')
                return redirect('payment:checkout')


@csrf_exempt
def sslc_status(request):
    if request.method == 'post' or request.method == 'POST':
        payment_data = request.POST
        status = payment_data['status']
        if status == 'VALID':
            val_id = payment_data['val_id']
            tran_id = payment_data['tran_id']
            return HttpResponseRedirect(reverse('payment:sslc_complete', kwargs={'val_id': val_id, 'tran_id': tran_id}))

    return render(request, 'store/status.html')

def sslc_complete(request, val_id, tran_id):
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    order = order_qs[0]
    order.ordered = True
    order.order_id = val_id
    order.payment_id = tran_id
    order.payment_method = 'SSLcommerz'
    order.save()
    cart_items = Cart.objects.filter(user=request.user, purchased=False)
    for item in cart_items:
        item.purchased = True
        item.save()
    
    return redirect('store:index')

def paypalPaymentMethod(request):
    data = json.loads(request.body)
    order_id = data['order_id']
    payment_id = data['payment_id']
    status = data['status']

    if status == "COMPLETED":
        if request.user.is_authenticated:
            order_qs = Order.objects.filter(user=request.user, ordered=False)
            order = order_qs[0]
            order.ordered = True
            order.order_id = order_id
            order.payment_id = payment_id
            order.payment_method = 'PayPal'
            order.save()
            cart_items = Cart.objects.filter(user=request.user, purchased=False)
            for item in cart_items:
                item.purchased = True
                item.save()
    return redirect('store:index')

payment/templates/payment/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Checkout {% endblock title %}

{% block content %}

<main class="main">
    <div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
        <div class="container">
            <h1 class="page-title">Checkout<span>Shop</span></h1>
        </div><!-- End .container -->
    </div><!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Shop</a></li>
                <li class="breadcrumb-item active" aria-current="page">Checkout</li>
            </ol>
        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="checkout">
            <div class="container">
                <div class="checkout-discount">
                    <form action="#">
                        <input type="text" class="form-control" required id="checkout-discount-input">
                        <label for="checkout-discount-input" class="text-truncate">Have a coupon? <span>Click here to
                                enter your code</span></label>
                    </form>
                </div><!-- End .checkout-discount -->
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-9">
                            <h2 class="checkout-title">Billing Details</h2><!-- End .checkout-title -->
                            {{billing_address.as_p}}


                            <label>Order notes (optional)</label>
                            <textarea class="form-control" cols="30" rows="4"
                                placeholder="Notes about your order, e.g. special notes for delivery"></textarea>
                        </div><!-- End .col-lg-9 -->
                        <aside class="col-lg-3">
                            <div class="summary">
                                <h3 class="summary-title">Your Order</h3><!-- End .summary-title -->

                                <table class="table table-summary">
                                    <thead>
                                        <tr>
                                            <th>Product</th>
                                            <th>Total</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        {% for item in order_item %}
                                        <tr>
                                            <td><a href="#">{{item.item.title}}</a></td>
                                            {% if item.get_total %}
                                            <td>$ {{ item.get_total }}</td>
                                            {% elif item.variation_single_price %}
                                            <td>$ {{item.variation_single_price}}</td>
                                            {% elif item.variation_total %}
                                            <td>$ {{item.variation_total}}</td>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}

                                        <tr class="summary-subtotal">
                                            <td>Subtotal:</td>
                                            <td>$ {{order_total}}</td>
                                        </tr><!-- End .summary-subtotal -->
                                        <tr>
                                            <td>Shipping:</td>
                                            <td>Free shipping</td>
                                        </tr>
                                        <tr class="summary-total">
                                            <td>Total:</td>
                                            <td>$ {{order_total}}</td>
                                        </tr><!-- End .summary-total -->
                                    </tbody>
                                </table><!-- End .table table-summary -->

                                <div class="accordion-summary" id="accordion-payment">
                                    <div class="card">{{payment_method.as_p}} </div>
                                    <br>
                                    <div id="paypal-button-container" style="display: none;"></div></div>
                                    <br>
                                </div><!-- End .accordion -->

                                <button id="preced-to-checkout" type="submit" class="btn btn-outline-primary-2 btn-order btn-block">
                                    <span class="btn-text">Place Order</span>
                                    <span class="btn-hover-text">Proceed to Checkout</span>
                                </button>
                            </div><!-- End .summary -->
                        </aside><!-- End .col-lg-3 -->
                    </div><!-- End .row -->
                </form>
            </div><!-- End .container -->
        </div><!-- End .checkout -->
    </div><!-- End .page-content -->
</main><!-- End .main -->

{% endblock content %}

{% block paypal %}

<script src="https://www.paypal.com/sdk/js?client-id={{paypal_client_id}}"></script>

<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    var url = "{% url 'payment:paypal_payment' %}"

    paypal.Buttons({
        createOrder: (data, actions) => {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: '{{order_total}}'
                    }
                }]
            });
        },

        onApprove: (data, actions) => {
            return actions.order.capture().then(function (details) {
                console.log(details)
                sendData();
                function sendData() {
                    fetch(url, {
                        method: "POST",
                        headers: {
                            'Content-type': "application/json",
                            'X-CSRFToken': csrftoken
                        },
                        body: JSON.stringify({
                            'order_id': details.id,
                            'payment_id': details.payer.payer_id,
                            'status': details.status,
                        }),
                    })
                }
                window.location.href = "{% url 'store:index' %}";
            });
        }
    }).render('#paypal-button-container');

        // JavaScript to toggle PayPal button visibility
        document.addEventListener('DOMContentLoaded', function () {
        const paymentMethodSelect = document.querySelector('select[name="payment_method"]');
        const paypalButtonContainer = document.getElementById('paypal-button-container');
        const procedToCheckout = document.getElementById('preced-to-checkout');

        paymentMethodSelect.addEventListener('change', function () {
            if (this.value === 'PayPal') {
                paypalButtonContainer.style.display = 'block';
                procedToCheckout.style.display = 'none';
            } else {
                paypalButtonContainer.style.display = 'none';
                procedToCheckout.style.display = 'block';
            }
        });

        // Trigger change event on page load to set initial visibility
        paymentMethodSelect.dispatchEvent(new Event('change'));
    });

</script>
{% endblock paypal %}